export const strangeTopics = {
	en: [
		"Should tomatoes be promoted from fruits to emotional support vegetables?",
		"Should escalators be allowed to choose their own direction every morning?",
		"Should fish wear glasses to improve underwater reading?",
		"Should people get timeouts for walking too slowly in public?",
		"Is toast just bread taking a victory lap?",
		"Should librarians be in charge of controlling the weather through silence?",
		"Are umbrellas secretly discouraging rain from trying its best?",
		"Should naps be recognized as an official national sport?",
		"Are bees just tiny flying entrepreneurs?",
		"Should shadows be considered a person's darkest accessory?",
		"If clouds had wheels, should they follow traffic laws?",
		"Are pancakes just breakfast frisbees?",
		"Should moonlight count as solar power after dark?",
		"Are shoelaces just tiny negotiators between feet and shoes?",
		"Is chewing gum just a workout for your face?",
		"Should blankets be promoted to emotional support furniture?",
		"Should dragons be hired as aviation consultants?",
		"Are crayons the tastiest-looking art supplies?",
		"Should weekends automatically be three days long?",
		"Are doors just dramatic interruptions in walls?",
		"Should ghosts have to pay rent if they haunt a house full-time?",
		"Should squeaky sneakers be banned from quiet buildings?",
		"Are bananas the most dramatic fruit because they bruise emotionally?",
		"Should birdsong come with subtitles?",
		"Is a refrigerator just a time machine for leftovers?",
		"Is invisible ink more honest because it admits it has nothing to say?",
		"Are eyebrows just punctuation marks for the face?",
		"Should teachers receive homework from students once a month for fairness?",
		"Are potatoes secretly the philosophers of vegetables?",
		"Is a candle just fire in a tiny prison?",
		"Should snowmen be considered seasonal workers?",
		"Is Wi-Fi basically modern oxygen for students?",
		"Is pizza crust just the bread handle of the meal?",
		"Should dolphins be exempt from taxes for being too charismatic?",
		"Are sunglasses just windows for your eyes?",
		"Is soup merely a beverage with ambition?",
		"Should yawning count as emotional plagiarism when someone else starts it?",
		"Are stairs just low-tech mountains?",
		"Should hats be considered portable roofs?",
		"Should ducks be allowed to moderate political debates?",
		"Do cereal boxes overpromise the excitement of breakfast?",
		"Should socks come with GPS trackers by law?",
		"Should Thursday night legally count as the weekend?",
		"Can cake become breakfast if eaten with enough confidence?",
		"Are pencils just wooden idea-launchers?",
		"Should vacuum cleaners be distrusted for being too loud?",
		"Should keyboards have a whisper mode for dramatic typing?",
		"Should tiny crayons be allowed to retire with honors?",
		"Should scarecrows receive awards for outstanding field work?",
		"Should books be allowed to judge people by their covers as revenge?",
		"Is a trampoline just an optimistic floor?",
		"Should vending machines be allowed to reject rude customers?",
		"Are dreams unpaid internships for the imagination?",
		"Should forks be classified as tiny food tridents?",
		"Is sunshine just daylight showing off?",
		"Should school uniforms include capes for morale?",
		"Is a map just a very confident flat lie?",
		"Should snail pace be recognized as an official unit of patience?",
		"Should robots feel insulted when called calculators?",
		"Is bubble wrap a legitimate musical instrument?",
		"Should fruit stickers become collectible currency?",
		"Is a bathtub just a personal indoor pond?",
		"Should pillows be promoted to bedtime consultants?",
		"Is an avocado just butter pretending to be healthy?",
		"Should elevators play dramatic music during awkward silence?",
		"Are fingerprints just nature's autographs?",
		"Should Mondays come with apology coupons?",
		"Are noodles without sauce emotionally incomplete?",
		"Should seagulls need airport clearance near beaches?",
		"Is a beard just a reusable scarf for the face?",
		"Should crayons and markers settle artistic disputes in court?",
		"Is sandwich crust just a security fence for the filling?",
		"Should clouds need building permits before becoming thunderstorms?",
		"Is glitter just arts-and-crafts chaos with confidence?",
		"Should students be graded on hallway walking technique?",
		"Is orange juice just liquid fruit confession?",
		"Should pigeons earn frequent flyer miles?",
		"Is a bench just a chair that learned teamwork?",
		"Should silence count as a conversation with the universe?",
		"Is a backpack just a turtle shell for students?",
		"Should cereal be eaten with chopsticks for discipline?",
		"Are calculators just tiny stress boxes with buttons?",
		"Should paper airplanes require a pilot's license?",
		"Is homework just school haunting your house?",
		"Should chairs have names if people sit in them every day?",
		"Are marshmallows just clouds that believed in themselves?",
		"Should mirrors charge people for repeated use?",
		"Is a hallway just a room that forgot to become a room?",
		"Should cats be hired as professional judges of character?",
		"Is popcorn the loudest possible way to eat corn?",
		"Should the last slice of pizza be protected by international law?",
		"Is a notebook just a parking lot for thoughts?",
		"Should alarm sounds be selected by a democratic vote?",
		"Are flip-flops just portable applause machines?",
		"Should bicycles have turn signals for dramatic effect?",
		"Is boredom just the brain buffering?",
		"Should coffee cups come with emotional warning labels?",
		"Is a spoon simply a tiny shovel for soup?",
		"Should whales be considered the philosophers of the ocean?",
		"Is a hoodie just a socially acceptable blanket?",
		"Should traffic lights be allowed to take personal days?",
		"Are erasers proof that mistakes deserve second chances?"
	],
	vi: [
		"Cà chua có nên được thăng chức từ trái cây thành rau củ hỗ trợ cảm xúc không?",
		"Thang cuốn có nên được tự chọn hướng đi của mình mỗi sáng không?",
		"Cá có nên đeo kính để đọc dưới nước tốt hơn không?",
		"Mọi người có nên bị phạt đứng góc nếu đi quá chậm ở nơi công cộng không?",
		"Bánh mì nướng có phải chỉ là bánh mì đang ăn mừng chiến thắng không?",
		"Thủ thư có nên phụ trách điều khiển thời tiết bằng sự im lặng không?",
		"Ô dù có đang bí mật làm mưa nản lòng không?",
		"Ngủ trưa có nên được công nhận là một môn thể thao quốc gia chính thức không?",
		"Ong có phải chỉ là những doanh nhân tí hon biết bay không?",
		"Cái bóng có nên được xem là phụ kiện u ám nhất của một con người không?",
		"Nếu mây có bánh xe, chúng có nên phải tuân theo luật giao thông không?",
		"Bánh pancake có phải chỉ là đĩa ném của bữa sáng không?",
		"Ánh trăng có nên được tính là năng lượng mặt trời ban đêm không?",
		"Dây giày có phải chỉ là những nhà đàm phán tí hon giữa bàn chân và đôi giày không?",
		"Kẹo cao su có phải chỉ là bài tập gym cho khuôn mặt không?",
		"Chăn có nên được thăng chức thành đồ nội thất hỗ trợ cảm xúc không?",
		"Rồng có nên được thuê làm cố vấn hàng không không?",
		"Bút sáp màu có phải là dụng cụ mỹ thuật trông ngon nhất không?",
		"Cuối tuần có nên mặc định dài ba ngày không?",
		"Cánh cửa có phải chỉ là những sự ngắt quãng đầy kịch tính trên bức tường không?",
		"Ma có nên phải trả tiền thuê nhà nếu ám một căn nhà toàn thời gian không?",
		"Giày thể thao kêu cót két có nên bị cấm vào những nơi cần yên tĩnh không?",
		"Chuối có phải là loại trái cây kịch tính nhất vì quá dễ bầm dập về cảm xúc không?",
		"Tiếng chim hót có nên có phụ đề không?",
		"Tủ lạnh có phải chỉ là cỗ máy thời gian dành cho đồ ăn thừa không?",
		"Mực vô hình có trung thực hơn vì nó thừa nhận mình chẳng có gì để nói không?",
		"Lông mày có phải chỉ là dấu câu của khuôn mặt không?",
		"Học sinh có nên giao bài tập về nhà cho giáo viên mỗi tháng một lần để công bằng không?",
		"Khoai tây có phải là những nhà triết học bí mật của thế giới rau củ không?",
		"Nến có phải chỉ là lửa bị nhốt trong một nhà tù tí hon không?",
		"Người tuyết có nên được xem là lao động thời vụ không?",
		"Wi-Fi có phải về cơ bản là oxy hiện đại của sinh viên không?",
		"Viền bánh pizza có phải chỉ là cái tay cầm bằng bánh mì của bữa ăn không?",
		"Cá heo có nên được miễn thuế vì quá cuốn hút không?",
		"Kính râm có phải chỉ là cửa sổ dành cho đôi mắt không?",
		"Súp có phải chỉ là một loại đồ uống đầy tham vọng không?",
		"Ngáp có nên được tính là đạo nhái cảm xúc khi ai đó ngáp trước không?",
		"Cầu thang có phải chỉ là núi phiên bản công nghệ thấp không?",
		"Mũ có phải nên được xem là mái nhà di động không?",
		"Vịt có nên được phép làm người điều phối các cuộc tranh luận chính trị không?",
		"Hộp ngũ cốc có đang hứa hẹn quá mức về độ thú vị của bữa sáng không?",
		"Tất có nên bắt buộc đi kèm thiết bị định vị GPS không?",
		"Tối thứ Năm có nên được tính hợp pháp là cuối tuần không?",
		"Bánh ngọt có thể trở thành bữa sáng nếu được ăn với đủ tự tin không?",
		"Bút chì có phải chỉ là bệ phóng ý tưởng bằng gỗ không?",
		"Máy hút bụi có đáng bị nghi ngờ vì quá ồn ào không?",
		"Bàn phím có nên có chế độ gõ thì thầm cho những lúc muốn tạo kịch tính không?",
		"Những mẩu bút sáp quá ngắn có nên được cho nghỉ hưu danh dự không?",
		"Bù nhìn có nên nhận giải thưởng vì thành tích xuất sắc ngoài đồng không?",
		"Sách có nên được quyền phán xét con người qua bìa ngoài để trả đũa không?",
		"Bạt nhún có phải chỉ là một cái sàn đầy lạc quan không?",
		"Máy bán hàng tự động có nên được phép từ chối khách hàng bất lịch sự không?",
		"Giấc mơ có phải là kỳ thực tập không lương của trí tưởng tượng không?",
		"Nĩa có nên được phân loại là cây đinh ba tí hon dành cho thức ăn không?",
		"Ánh nắng có phải chỉ là ban ngày đang khoe mẽ không?",
		"Đồng phục học sinh có nên bao gồm áo choàng để tăng sĩ khí không?",
		"Bản đồ có phải chỉ là một lời nói dối rất tự tin trên mặt phẳng không?",
		"Tốc độ ốc sên có nên được công nhận là đơn vị đo độ kiên nhẫn chính thức không?",
		"Robot có nên cảm thấy bị xúc phạm khi bị gọi là máy tính cầm tay không?",
		"Xốp nổ có phải là một nhạc cụ hợp pháp không?",
		"Tem dán trên trái cây có nên trở thành tiền tệ sưu tầm không?",
		"Bồn tắm có phải chỉ là cái ao trong nhà dành riêng cho một người không?",
		"Gối có nên được thăng chức thành cố vấn giờ đi ngủ không?",
		"Bơ có phải chỉ là bơ động vật giả vờ sống lành mạnh không?",
		"Thang máy có nên phát nhạc kịch tính trong những khoảng lặng ngượng ngùng không?",
		"Dấu vân tay có phải chỉ là chữ ký của tự nhiên không?",
		"Thứ Hai có nên đi kèm phiếu xin lỗi không?",
		"Mì không sốt có phải đang dang dở về mặt cảm xúc không?",
		"Mòng biển có nên cần giấy phép điều phối hàng không gần bãi biển không?",
		"Râu có phải chỉ là chiếc khăn quàng tái sử dụng cho khuôn mặt không?",
		"Bút sáp và bút lông có nên giải quyết tranh chấp nghệ thuật trước tòa không?",
		"Viền sandwich có phải chỉ là hàng rào an ninh cho phần nhân không?",
		"Mây có nên cần giấy phép xây dựng trước khi trở thành giông bão không?",
		"Kim tuyến có phải chỉ là hỗn loạn thủ công mỹ nghệ nhưng rất tự tin không?",
		"Học sinh có nên được chấm điểm kỹ thuật đi ngoài hành lang không?",
		"Nước cam có phải chỉ là lời thú tội ở dạng lỏng của trái cây không?",
		"Bồ câu có nên được tích điểm khách hàng bay thường xuyên không?",
		"Ghế băng có phải chỉ là cái ghế đã học được tinh thần đồng đội không?",
		"Sự im lặng có nên được tính là một cuộc trò chuyện với vũ trụ không?",
		"Ba lô có phải chỉ là mai rùa dành cho học sinh không?",
		"Ngũ cốc có nên được ăn bằng đũa để rèn kỷ luật không?",
		"Máy tính cầm tay có phải chỉ là những chiếc hộp stress tí hon đầy nút bấm không?",
		"Máy bay giấy có nên cần bằng lái phi công không?",
		"Bài tập về nhà có phải chỉ là trường học ám chính ngôi nhà của bạn không?",
		"Ghế có nên có tên riêng nếu người ta ngồi lên nó mỗi ngày không?",
		"Kẹo marshmallow có phải chỉ là những đám mây đã tin vào chính mình không?",
		"Gương có nên thu phí những người soi quá nhiều lần không?",
		"Hành lang có phải chỉ là một căn phòng quên mất cách trở thành căn phòng không?",
		"Mèo có nên được tuyển làm chuyên gia phán xét tính cách con người không?",
		"Bắp rang có phải là cách ồn ào nhất để ăn ngô không?",
		"Miếng pizza cuối cùng có nên được bảo vệ bởi luật pháp quốc tế không?",
		"Sổ tay có phải chỉ là bãi đỗ xe dành cho suy nghĩ không?",
		"Âm báo thức có nên được chọn bằng bỏ phiếu dân chủ không?",
		"Dép xỏ ngón có phải chỉ là cỗ máy vỗ tay di động không?",
		"Xe đạp có nên có xi nhan chỉ để tăng độ kịch tính không?",
		"Chán nản có phải chỉ là bộ não đang tải đệm không?",
		"Cốc cà phê có nên đi kèm nhãn cảnh báo cảm xúc không?",
		"Muỗng có phải chỉ là chiếc xẻng tí hon dành cho súp không?",
		"Cá voi có phải là những nhà triết học của đại dương không?",
		"Áo hoodie có phải chỉ là chiếc chăn được xã hội chấp nhận không?",
		"Đền giao thông có nên được phép xin nghỉ phép cá nhân không?",
		"Cục tẩy có phải là bằng chứng rằng sai lầm xứng đáng có cơ hội thứ hai không?"
	]
};
